---
galaxy_info:
  description: StackStorm role to create system user, on whose behalf remote/local action runners would work
  author: armab
  company: StackStorm
  license: Apache
  min_ansible_version: 1.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - system
dependencies: []
