---
- name: Install RPM key for StackStorm
  become: yes
  rpm_key:
    state: present
    key: https://packagecloud.io/StackStorm/stable/gpgkey

- name: Add ST2 Repo
  become: yes
  yum_repository:
    name: stackstorm
    description: Stackstorm Repo
    file: st2
    baseurl: https://packagecloud.io/StackStorm/stable/el/$releasever/$basearch
