---
- name: Add ST2 Repo
  become: yes
  yum_repository:
    name: "StackStorm_{{ st2_pkg_repo }}"
    description: "StackStorm_{{ st2_pkg_repo }}"
    file: "StackStorm_{{ st2_pkg_repo }}"
    baseurl: https://packagecloud.io/StackStorm/{{ st2_pkg_repo }}/el/{{ ansible_distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgkey: "https://packagecloud.io/StackStorm/{{ st2_pkg_repo }}/gpgkey"
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    gpgcheck: no
    enabled: yes
    sslverify: yes
  register: st2_repo_installed

# Fixes "Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: StackStorm_stable. Please verify its path and try again" when installing st2
- name: Refresh repo list
  become: yes
  shell: yum -y repolist
  when: st2_repo_installed.changed == true  # Helps ensure idempotency
