---
galaxy_info:
  description: Install custom OpenStack Mistral, patched by StackStorm
  author: armab
  company: StackStorm
  license: Apache
  min_ansible_version: 1.9.1
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
        - 6
        - 7
  categories:
    - system
dependencies:
  - role: postgresql
  - role: st2repos
