---
galaxy_info:
  description: Determine if system requirements were met to install StackStorm
  author: armab
  company: StackStorm
  license: Apache
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - system
dependencies: []
