---
- hosts: all
  tasks:
  # See: https://github.com/StackStorm/ansible-st2/pull/55
  - fail: msg="This playbook doesn't work with Ansible 2.2 or greater. Use 2.1 instead."
    when: ansible_version.full >= "2.2"

  - name: Install galaxy dependencies
    command: ansible-galaxy install -r roles/mistral/requirements.yml
    delegate_to: 127.0.0.1
    run_once: true
